/* SAFE — News rotation */
(function(){
  'use strict';

  var items = [
    { date:'May 1 2026', region:'Global', category:'Democracy', emoji:'📚', title:'Student Journalism Brings Hope for Democracy', desc:'University student journalists published a powerful editorial today reflecting on the anxiety of the current global political climate. Their conclusion was deeply uplifting: the passionate, truth-seeking nature of today\'s student journalists is exactly the tool needed to build a more transparent future.', link:'https://www.thebucknellian.com', linkLabel:'Read' },
    { date:'May 1 2026', region:'Global', category:'Innovation', emoji:'💡', title:'Young Winner Uses AI for Good', desc:'A brilliant young student won a major science award for using artificial intelligence to design a new molecule aimed at solving pressing global health and environmental challenges. Proof of the positive potential of next-generation technology in youth hands.', link:'https://www.globalcitizen.org', linkLabel:'Read' },
    { date:'May 1 2026', region:'Global', category:'Heroism', emoji:'🥸', title:'Middle Schoolers Turn Heroes on the School Bus', desc:'A group of quick-thinking middle school students calmly worked together to safely stop their school bus when the driver experienced a sudden medical emergency at the wheel. Their quick thinking and composure saved everyone on board.', link:'https://www.sunnyskyzsz.com', linkLabel:'Read' },
    { date:'May 1 2026', region:'Europe', category:'Youth', emoji:'🌏', title:'European Youth Week Champions "Solidarity and Fairness"', desc:'The 2026 European Youth Week wrapped up today with thousands of young people across the continent participating in civic events. The week celebrated 30 years of European youth volunteering, showcasing teenagers who have made measurable, positive differences in their local societies.', link:'https://youth.europa.eu', linkLabel:'Read' },
    { date:'May 1 2026', region:'UK', category:'Housing', emoji:'🏠', title:'Youth Organisers Celebrate Historic Renters Rights Win', desc:'The long-awaited Renters Rights Act officially took effect today in England, banning "no-fault" evictions. This monumental victory was heavily championed by youth-driven community unions like Acorn. Young organisers spent over a decade campaigning for these protections to secure stable housing for millions of young renters.', link:'https://www.positive.news', linkLabel:'Read' },
    { date:'Apr 30 2026', region:'UK', category:'Environment', emoji:'🐦', title:'The Gen Z Birdwatching Boom', desc:'A new study published by the RSPB revealed a massive 1,088% increase in 16-to-29-year-olds regularly birdwatching in Britain since 2018. Young people are using it as a way to ditch their screens, find moments of peace, and reconnect with local nature.', link:'https://www.theguardian.com', linkLabel:'Read' },
    { date:'Apr 30 2026', region:'South America', category:'Community', emoji:'🤝', title:'Teens Bridge the Generational Gap in Chile', desc:'A group of youth volunteers in Rancagua, Chile, organised a massive local effort to paint and repair 20 homes for local senior citizens. Working alongside the national programme for elderly adults, the teens spent their weekend ensuring their older neighbours felt seen, supported, and valued.', link:'https://www.churcharticles.org', linkLabel:'Read' },
    { date:'Apr 29 2026', region:'North America', category:'Environment', emoji:'🌱', title:'"Green Crew" Inspires the Next Generation', desc:'TIME for Kids highlighted 18-year-old Hannah Stockert Barisonski, who founded the "Green Crew" when she was just 13. Based in Minnesota, the youth-led group has successfully mobilised hundreds of children to actively protect their local environment, proving that you are never too young to start a conservation movement.', link:'https://www.timeforkids.com', linkLabel:'Read' },
    { date:'Apr 29 2026', region:'Global', category:'Digital', emoji:'📱', title:'Kids Teaching Kids Digital Empathy', desc:'The youth news podcast KidNuz launched a brilliant new series called "Kids Showing Kids How to Be Good Online Citizens." Instead of adults lecturing teens about screen time, the initiative empowers young people to teach their peers about digital empathy and how to navigate the internet kindly.', link:'https://www.kidnuz.org', linkLabel:'Listen' },
    { date:'Apr 28 2026', region:'UK', category:'Community', emoji:'🚘', title:'Bingley Firefighters announce "72 for the 72" community challenge', desc:'Firefighters from Bingley Fire Station are preparing a special "72 for the 72" charity challenge on May 3rd, covering 72 miles in memory of those lost at Grenfell. Opening station doors to the public, focusing on community solidarity and giving youth a chance to meet the crew.', link:'https://www.westyorksfire.gov.uk/news/bingley-firefighters-take-72-mile-challenge-ahead-grenfell-tower-anniversary', linkLabel:'Read' },
    { date:'Apr 27 2026', region:'UK', category:'Community', emoji:'🎉', title:'"One Heart, One Community" Festival - youth-led resilience project', desc:'The Youth Action Alliance in London is running a beautiful, community-driven campaign funding a free festival in June 2026 for over 2,500 residents. While honouring remembrance, the festival supports local young people, creates space for joy, and reminds residents they are valued.', link:'https://www.crowdfunder.co.uk/p/one-heart-1', linkLabel:'Read' },
    { date:'Apr 26 2026', region:'UK', category:'Health', emoji:'👀', title:'Great Ormond Street Hospital breakthrough in treating childhood blindness', desc:'Groundbreaking work treating Leber\'s congenital amaurosis (LCA), a genetic mutation causing infant blindness, is giving young people like Saffie Sandford from Hertfordshire profound improvements in their ability to see the world around them. A massive leap forward in youth healthcare.', link:'https://www.positive.news/society/good-news-stories-from-week-17-of-2026/', linkLabel:'Read' },
    { date:'Apr 25 2026', region:'Global', category:'Youth', emoji:'🚀', title:'Youth volleyball team turns tornado evacuation into joy and community', desc:'A couple\'s wedding was interrupted by tornado alarms, forcing evacuation. A youth volleyball group taking shelter in the same basement joined them, turning a scary situation into an impromptu dance party and photo session - proving young people bring joy in crisis.', link:'https://podcasts.apple.com/us/podcast/the-positive-truth-uplifting-news-positive-news/id1169234042', linkLabel:'Listen' },
    { date:'Apr 24 2026', region:'Global', category:'Climate', emoji:'🌎', title:'Goldman Environmental Prize recognises youth-led climate victories worldwide', desc:'South Korea\'s Borim Kim wins prestigious award for the first youth-led climate litigation case in Asia, proving young voices have the power to enact monumental, structural change. UK\'s Sarah Finch also honoured for her landmark legal win against big oil.', link:'https://www.positive.news/society/good-news-stories-from-week-17-of-2026/', linkLabel:'Read' },
    { date:'Apr 21 2026', region:'Global', category:'Youth Service', emoji:'🌍', title:'Global Youth Service Day - thousands mobilise this weekend', desc:'This coming weekend marks the peak of Global Youth Service Month. Thousands of young people across the UK and worldwide are registered for community service - from cleanup events to intergenerational tech cafes.', link:'https://www.ysa.org/38th-annual-global-youth-service-day-april-24-26-2026-youth-service-month', linkLabel:'Read' },
    { date:'Apr 20 2026', region:'Global', category:'Climate', emoji:'🌎', title:'"Green Nobel" winners announced - youth leading the charge', desc:'Goldman Environmental Prize 2026 highlights Borim Kim from South Korea, whose youth-led climate lawsuit forced ambitious emissions targets and inspired similar movements across Asia. Proof that young people are reshaping climate policy.', link:'https://news.mongabay.com/2026/04/meet-the-2026-goldman-environmental-prize-winners/', linkLabel:'Read' },
    { date:'Apr 18 2026', region:'Global', category:'Youth', emoji:'🌐', title:'UN ECOSOC Youth Forum: Gen Z redesigns solutions for 2030', desc:'Young leaders gathered at UN HQ for "Innovate, Unite and Transform" to showcase how Gen Z is actively building solutions for clean water, sustainable cities, and climate action.', link:'https://news.un.org/en/story/2026/04/1067972', linkLabel:'Read' },
    { date:'Apr 18 2026', region:'Global', category:'Climate', emoji:'🔥', title:'Direct funding now reaches young climate leaders under 30', desc:'UNDP and Italy launch Youth4Climate funding that bypasses bureaucracy, putting resources directly into the hands of young innovators leading local environmental projects.', link:'https://climatepromise.undp.org', linkLabel:'Read' },
    { date:'Apr 17 2026', region:'UK', category:'Environment', emoji:'🌍', title:'Sarah Finch wins landmark climate case - game-changer for youth campaigners', desc:'A UK legal precedent that has become transformative for young environmental advocates. Her victory has already been used to block new oil and coal projects, securing a cleaner future for the next generation.', link:'https://www.theguardian.com/environment/2026/apr/woman-environmental-case-goldmanprize', linkLabel:'Read' },
    { date:'Apr 16 2026', region:'UK', category:'Arts', emoji:'🎛', title:'National Youth Orchestra "Collide" series receives rave reviews', desc:'Hundreds of young musicians under conductor Alpesh Chauhan demonstrated "remarkable intensity" - proving the arts are thriving among UK youth despite economic pressures on school music programmes.', link:'https://www.theguardian.com/music/2026/apr/national-youth-orchestra-collide-review', linkLabel:'Read' },
    { date:'Apr 15 2026', region:'UK', category:'Community', emoji:'🤲', title:'Grenfell Foundation youth programmes empower next generation', desc:'The Grenfell Children and Young People\'s Fund continues multi-year support: youth workers, community projects, boxing training through Fight 4 Grenfell, and artist collaborations with survivors - rebuilding with healing and agency at the centre.', link:'https://www.grenfellfoundation.org.uk/community-projects', linkLabel:'Read' },
    { date:'Apr 15 2026', region:'UK', category:'SAFE', emoji:'✍️', title:'SAFE petition crosses its first milestone', desc:'The public mandate for the UK\'s first holistic youth development hub is building. Every signature becomes evidence of demand - data that funders, councils and partners cannot ignore.', link:'https://www.change.org/p/build-the-uk-s-first-holistic-youth-development-hub-to-transform-at-risk-lives', linkLabel:'Sign' },
    { date:'Apr 8 2026', region:'Africa', category:'Reforestation', emoji:'🌳', title:'Great Green Wall crosses 30% of Sahel target', desc:'A continent-wide effort to restore 100 million hectares of degraded land across the Sahel is now past 30% complete in participating nations, according to UNCCD updates. Jobs, food security and biodiversity moving in the right direction.', link:'https://www.unccd.int/our-work/ggwi', linkLabel:'Read' },
    { date:'Apr 1 2026', region:'Global', category:'Health', emoji:'🎫', title:'Global child mortality at record lows', desc:'UN figures show under-five child mortality has more than halved since 2000. Still too high - but the trend is unambiguous. Vaccines, clean water, maternal care and education working together.', link:'https://data.unicef.org/topic/child-survival/under-five-mortality/', linkLabel:'Read' },
    { date:'Mar 25 2026', region:'UK', category:'Youth', emoji:'🛶', title:'Record low youth reoffending in boroughs with open community hubs', desc:'Boroughs that kept youth centres open through the 2010s continue to show measurably lower reoffending rates than comparable boroughs that closed theirs. Corroborates the SAFE thesis: place matters.', link:'https://www.gov.uk/government/collections/youth-justice-statistics', linkLabel:'Read' },
    { date:'Mar 18 2026', region:'Global', category:'Energy', emoji:'🔌', title:'Renewables now account for the majority of new power capacity', desc:'The IEA reports that for the third year running, more than 80% of all new electricity capacity added globally came from renewables. Cost, not politics, is doing the work.', link:'https://www.iea.org/reports/renewables-2024', linkLabel:'Read' },
    { date:'Mar 11 2026', region:'South America', category:'Literacy', emoji:'📖', title:'Adult literacy programmes double enrolment in rural Brazil', desc:'State-run literacy and numeracy evening schools in rural Brazilian municipalities report record enrolment, particularly from women over 40 returning to formal education for the first time.', link:'https://en.unesco.org/themes/literacy', linkLabel:'Read' },
    { date:'Mar 4 2026', region:'Asia', category:'Ocean', emoji:'🌅', title:'Coral restoration at scale off the Philippines', desc:'Community-led reef restoration is producing visible regrowth on previously bleached sites. Simple design. Local labour. Patience. Works where top-down policy has not.', link:'https://www.iucn.org/our-work/topic/coral-reefs', linkLabel:'Read' },
    { date:'Feb 25 2026', region:'Europe', category:'Mental Health', emoji:'💭', title:'Peer-led youth mental health pilots outperform traditional triage', desc:'Several European pilots show that youth-peer-led early intervention produces better engagement and outcomes than adult clinician-only pathways. Young people listen to young people first.', link:'https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health', linkLabel:'Read' },
    { date:'Feb 18 2026', region:'Global', category:'Science', emoji:'💻', title:'Global polio cases at an all-time low', desc:'Wild polio remains endemic in only two countries. A disease that paralysed hundreds of thousands per year is now measured in single and double digits. Proof that coordinated, sustained effort works.', link:'https://polioeradication.org/', linkLabel:'Read' },
    { date:'Feb 11 2026', region:'Global', category:'Conservation', emoji:'🐋', title:'Humpback whale population rebounds 90% from near-extinction', desc:'From roughly 450 in the 1950s to more than 25,000 today in the Southern Hemisphere. Moratoriums work. The recovery is slow, unglamorous, and absolute.', link:'https://iwc.int/', linkLabel:'Read' },
    { date:'Feb 4 2026', region:'Kenya', category:'Education', emoji:'📚', title:'Kenyan free digital libraries reach 1 million rural learners', desc:'Solar-powered, offline-first tablet libraries now serve over a million rural students. Books in local languages, science in Swahili, no electricity required.', link:'https://www.unicef.org/education', linkLabel:'Read' },
    { date:'Jan 28 2026', region:'Global', category:'Poverty', emoji:'💵', title:'Extreme poverty rate at lowest level on record', desc:'The share of humanity living under $2.15/day continues a four-decade decline. The last mile is the hardest - concentrated in fragile states - but the direction is unambiguous.', link:'https://www.worldbank.org/en/topic/poverty', linkLabel:'Read' }
  ];

  function render(){
    var grid = document.getElementById('news-grid');
    if(!grid) return;

    var featured = items.slice(0, 9);

    grid.innerHTML = featured.map(function(it){
      var linkLabel = it.linkLabel || 'Read';
      return (
        '<article class="news-card">' +
          '<span class="news-globe">' + it.emoji + '</span>' +
          '<div class="news-meta"><span>' + it.region + '</span><span>' + it.category + '</span></div>' +
          '<span class="news-date">' + it.date + '</span>' +
          '<h3 class="news-title">' + it.title + '</h3>' +
          '<p class="news-desc">' + it.desc + '</p>' +
          '<a class="news-link" href="' + it.link + '" target="_blank" rel="noopener">' + linkLabel + ' &rarr;</a>' +
        '</article>'
      );
    }).join('');

    var banner = document.getElementById('news-week');
    if(banner){
      var now = new Date();
      var opts = { day:'numeric', month:'short', year:'numeric' };
      banner.innerHTML =
        '<span>Field Reports · Week 18</span>' +
        '<strong>What mainstream media won\'t highlight</strong>' +
        '<span>Latest · ' + now.toLocaleDateString('en-GB', opts) + '</span>';
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', render);
  } else {
    render();
  }
})();
